name: BCDLv1
channels:
  - pytorch
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.1.18
  - cffi=1.11.5
#  - cudatoolkit=8.0
  - freetype=2.8
  - imageio=2.3.0
  - intel-openmp=2018.0.0
  - jpeg=9b
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libpng=1.6.34
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - ncurses=6.0
  - numpy=1.14.2
  - olefile=0.45.1
  - openssl=1.0.2o
  - pillow=5.0.0
  - pip=9.0.3
  - pycparser=2.18
  - python=2.7.14
  - readline=7.0
  - scipy=1.0.1
  - setuptools=39.0.1
  - six=1.11.0
  - sqlite=3.22.0
  - tk=8.6.7
  - wheel=0.31.0
  - xz=5.2.3
  - zlib=1.2.11
  - pytorch=0.3.1
  - torchvision=0.2.0
  - pip:
    - backports-abc==0.4
    - backports.functools-lru-cache==1.5
    - backports.ssl-match-hostname==3.5.0.1
    - cycler==0.10.0
    - functools32==3.2.3.post2
    - ipython-genutils==0.1.0
    - ipywidgets==4.1.1
    - jsonschema==2.5.1
    - kiwisolver==1.0.1
    - matplotlib==2.2.2
    - nbformat==4.0.1
    - pandas==0.22.0
    - path.py==8.1.2
    - ptyprocess==0.5.1
    - pyparsing==2.2.0
    - python-dateutil==2.7.2
    - pytz==2018.4
    - seaborn==0.8.1
    - singledispatch==3.4.0.3
    - subprocess32==3.2.7
    - terminado==0.6
    - torch==0.3.1.post3
    - tornado==4.3
#    - pytorch=0.3.1=py27_cuda8.0.61_cudnn7.1.2_3
    - cudatoolkit=8.0
